package com.github.ankowals.framework.web.devtools;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Stream;
import javax.imageio.ImageIO;
import org.junit.jupiter.api.TestInfo;
import org.openqa.selenium.devtools.DevTools;
import org.openqa.selenium.devtools.v145.page.Page;

public class PageDomain {

  private static final Map<String, List<byte[]>> CACHE = new ConcurrentHashMap<>();
  private final DevTools devTools;

  PageDomain(DevTools devTools) {
    this.devTools = devTools;
  }

  public void enable() {
    this.devTools.send(Page.enable(Optional.empty()));
  }

  /*
  everyNthFrame is not time derived rather it is frames generated by Chrome.
  In case UI did not change (even for long time period), no frames would be sent.

  While UI is animating, every single frame is issued as a screencast event.
  Chrome will not send any more screencast events until the ack has been received.
  Having a low everyNthFrame will result in a smoother animation but a lot more screencast events.

  To optimize (speed up) the flow one can
    - increase the everyNthFrame
    - decrease the quality
    - ack the screencast as the first line of the listener implementation
    - cache image in memory and flush it to the disk offline
   */
  public void startScreencast(TestInfo testInfo) {
    this.addListener(this.key(testInfo));
    this.devTools.send(
        Page.startScreencast(
            Optional.of(Page.StartScreencastFormat.PNG), // format
            Optional.of(30), // quality
            Optional.of(1920), // maxWidth
            Optional.of(1080), // maxHeight
            Optional.of(3))); // everyNthFrame
  }

  public void stopScreencast() {
    this.devTools.send(Page.stopScreencast());
  }

  public void flush(TestInfo testInfo) {
    String key = this.key(testInfo);
    List<byte[]> imageBytes = CACHE.get(key);

    if (imageBytes != null) {
      imageBytes.clear();
      CACHE.remove(key);
    }
  }

  public boolean flush(Path screencastDir, TestInfo testInfo) {
    String key = this.key(testInfo);
    List<byte[]> imageBytes = CACHE.get(key);

    try {
      return this.doFlush(screencastDir, imageBytes);
    } finally {
      if (imageBytes != null) {
        imageBytes.clear();
        CACHE.remove(key);
      }
    }
  }

  private void addListener(String key) {
    CACHE.put(key, new ArrayList<>());
    List<byte[]> imageBytes = CACHE.get(key);

    this.devTools.addListener(
        Page.screencastFrame(),
        screencastFrame -> {
          this.devTools.send(Page.screencastFrameAck(screencastFrame.getSessionId()));
          imageBytes.add(Base64.getDecoder().decode(screencastFrame.getData()));
        });
  }

  private boolean doFlush(Path screencastDir, List<byte[]> imageBytes) {
    AtomicInteger counter = new AtomicInteger(0);

    imageBytes.forEach(
        bytes -> {
          try (ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(bytes)) {
            File file =
                Path.of(
                        screencastDir.toAbsolutePath().toString(),
                        "%s.png".formatted(counter.incrementAndGet()))
                    .toFile();

            ImageIO.write(ImageIO.read(byteArrayInputStream), "png", file);
          } catch (IOException e) {
            throw new RuntimeException(e); // NOSONAR
          }
        });

    try {
      return !this.isEmpty(screencastDir);
    } catch (IOException e) { // NOSONAR
      return false;
    }
  }

  private boolean isEmpty(Path path) throws IOException {
    if (Files.isDirectory(path)) {
      try (Stream<Path> entries = Files.list(path)) {
        return entries.findFirst().isEmpty();
      }
    }

    throw new IOException("Directory not found: " + path);
  }

  private String key(TestInfo testInfo) {
    return this.key(testInfo.getTestClass().orElseThrow(), testInfo.getDisplayName());
  }

  private String key(Class<?> testClass, String displayName) {
    return "%s.%s".formatted(testClass.getName(), displayName);
  }
}
